### ISSUE TITLE
[Bug] New DepLoader Crashes on Startup

### ISSUE THREAD

**Issue by djrecipe** [MyEssentials/MyEssentials-Core#5]
Copy this into notepad to see it with correct newlines:

[18:06:08] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:06:08] [main/DEBUG] [FML/]: Injecting coremod DepLoader {mytown.core.DepLoader} class transformers
[18:06:08] [main/DEBUG] [FML/]: Injection complete
[18:06:08] [main/DEBUG] [FML/]: Running coremod plugin for DepLoader {mytown.core.DepLoader}
[18:06:08] [main/DEBUG] [FML/]: Running coremod plugin DepLoader
[18:06:08] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.RuntimeException: java.lang.NullPointerException
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130) ~[FTBServer-1.7.10-1408.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [FTBServer-1.7.10-1408.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [FTBServer-1.7.10-1408.jar:?]
Caused by: java.lang.NullPointerException
	at mytown.core.deploader.Downloader.checkExisting(Downloader.java:31) ~[Downloader.class:?]
	at mytown.core.deploader.Downloader.load(Downloader.java:23) ~[Downloader.class:?]
	at mytown.core.deploader.DepLoader.load(DepLoader.java:54) ~[DepLoader.class:?]
	at mytown.core.DepLoader.call(DepLoader.java:20) ~[MyEssentials-Core-1.7.10-1.5r29-universal.jar:?]
	at mytown.core.DepLoader.call(DepLoader.java:15) ~[MyEssentials-Core-1.7.10-1.5r29-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:126) ~[FTBServer-1.7.10-1408.jar:?]
	... 8 more

**Comment by djrecipe** [comment]
For me, the bleeding edge build of MyTown2 works with MyEssentials-Core-1.7.10-1.5r25.

**Comment by legobear154** [comment]
Ok, that *should* fix that crash. I couldn't reproduce it on my end, so I am not sure why. But still :)
Our Jenkins server is down right now, but I will probably put a new release on CurseForge shortly.
